# Generated by Django 6.0.1 on 2026-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLotSize', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ColonyName', models.CharField(max_length=100)),
                ('AreaName', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
