# Generated by Django 6.0.1 on 2026-01-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='Pincode',
            new_name='PinCode',
        ),
    ]
